#!/usr/bin/env bash -e
#
# mpv
# https://github.com/mpv-player/mpv.git
#

set -e

PS4='+ ${BASH_SOURCE}:${LINENO}: '

error_report() {
    echo "Error on line $1"
}

trap 'error_report $LINENO' ERR

cd "$(dirname "$0")"
set -a; source build.env; set +a
source utils/pkg-import

pkgname="mpv"
pkgdir="$1"
with_bundle="$2"
srcdir="src/mpv"
worktree_basename="mpv-worktree-build"
script_dir="$(cd "$(dirname "$0")" && pwd)"
srcdir_abs="$script_dir/$srcdir"
worktree_dir="$script_dir/src/_worktrees/${worktree_basename}"
worktree_srcdir="${worktree_dir}"
builddir="$worktree_srcdir/build"
fixed_version_suffix="1"
base_version="$(sed -E 's/-UNKNOWN$//' "$srcdir_abs/MPV_VERSION")"
fixed_version="${base_version}-${fixed_version_suffix}"

import_local_pkg "$pkgdir"

import_homebrew_pkg libarchive

cleanup_worktree() {
  git -C "$srcdir_abs" worktree remove --force "$script_dir/../mpv-worktree-build" >/dev/null 2>&1 || true
  rm -rf "$script_dir/../mpv-worktree-build" >/dev/null 2>&1 || true

  git -C "$srcdir_abs" worktree remove --force "$worktree_dir" >/dev/null 2>&1 || true
  rm -rf "$worktree_dir" >/dev/null 2>&1 || true
}
trap cleanup_worktree EXIT

cleanup_worktree
mkdir -p "$(dirname "$worktree_dir")"

rm -rf "${builddir}"

git -C "$srcdir_abs" worktree add --force "$worktree_dir" HEAD

meson setup "${builddir}" "${worktree_srcdir}" \
  -Dmacos-touchbar=disabled \
  --prefix="${pkgdir}" \
  -Dmanpage-build=disabled \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dlua=luajit \
  # "$@"

meson compile -j$(sysctl -n hw.physicalcpu) -C "${builddir}"

meson install -C "${builddir}" --tags runtime,devel

if [ "$with_bundle" -eq 1 ]; then
  cd "$worktree_srcdir"
  ./TOOLS/osxbundle.py -s build/mpv

  info_plist="build/mpv.app/Contents/Info.plist"

  /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${fixed_version}" "${info_plist}" 2>/dev/null || \
  /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string ${fixed_version}" "${info_plist}"

  /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${fixed_version}" "${info_plist}" 2>/dev/null || \
  /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${fixed_version}" "${info_plist}"

  codesign --force -s - "build/mpv.app" >/dev/null 2>&1 || true

  if [ -d "/Applications/mpv.app" ]; then
    rm -rf /Applications/mpv.app
  fi
  mv build/mpv.app /Applications
fi

cleanup_worktree
# vi:set ts=2 sw=2 et:
