#!/usr/bin/env bash -e
#
# libass
# https://github.com/libass/libass.git
#

set -e

PS4='+ ${BASH_SOURCE}:${LINENO}: '

error_report() {
    echo "Error on line $1"
}

trap 'error_report $LINENO' ERR

cd "$(dirname "$0")"
set -a; source build.env; set +a
source utils/pkg-import

pkgname="libass"
pkgdir="$1"
srcdir="src/libass"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

rm -rf "${builddir}"
import_local_pkg $pkgdir

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Ddefault_library=shared \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dcoretext=enabled \
  -Dasm=enabled \
  -Dlibunibreak=enabled \
  -Dfontconfig=disabled \
  -Ddirectwrite=disabled \
  # "$@"

meson compile -C "${builddir}"

meson install -C "${builddir}"

rm -rf "${builddir}"

# vi:set ts=2 sw=2 et:
